AspNetCore.MVC/TurkcellBootcamp/Camp_301/MyAspNetCoreApp/MyAspNetCoreApp.Web/Models/Product.cs
namespace MyAspNetCoreApp.Web.Models
{
    public class Product
    {
        public int Id { get; set; }
        public string? Name { get; set; }
        public decimal Price { get; set; }
        public int Stock { get; set; }
        public string Description { get; set; }
        public string? Color { get; set; }
        public bool IsPublish { get; set; }
        public DateTime? PublishDate { get; set; }
        public int Expire { get; set; }
        public string? ImagePath { get; set; }
        public int CategoryId { get; set; }
        public Category Category { get; set; }
    }
}

AspNetCore.MVC/TurkcellBootcamp/Camp_301/MyAspNetCoreApp/MyAspNetCoreApp.Web/ViewModels/ProductViewModel.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;
using System.ComponentModel.DataAnnotations;

namespace MyAspNetCoreApp.Web.ViewModels
{
    public class ProductViewModel
    {
        public int Id { get; set; }
        [StringLength(50, ErrorMessage = "Name field can not be more than 50 characters")]
        [Required(ErrorMessage = "Name field is required")]
        [Remote(controller: "Product", action: "HasProductName")]
        public string? Name { get; set; }
        [Required(ErrorMessage = "Price field is required")]
        public decimal? Price { get; set; }
        [Required(ErrorMessage = "Stock field is required")]
        [Range(1, 200, ErrorMessage = "Please enter stock between 1 to 200")]
        public int? Stock { get; set; }
        [StringLength(300, MinimumLength = 10, ErrorMessage = "Description field should be in between 10 to 300 characters")]
        [Required(ErrorMessage = "Description field is required")]
        public string Description { get; set; }
        [Required(ErrorMessage = "Color field is required")]
        public string? Color { get; set; }
        public bool IsPublish { get; set; }
        [Required(ErrorMessage = "Publish Date field is required")]
        public DateTime? PublishDate { get; set; }
        [Required(ErrorMessage = "Expire field is required")]
        public int? Expire { get; set; }
        [EmailAddress(ErrorMessage = "Email address format is invalid")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Category field is required")]
        public int CategoryId { get; set; }
        public string? CategoryName { get; set; }
        [ValidateNever]
        public IFormFile? Image { get; set; }
        [ValidateNever]
        public string? ImagePath { get; set; }
    }
}

AspNetCore.MVC/TurkcellBootcamp/Camp_301/MyAspNetCoreApp/MyAspNetCoreApp.Web/Controllers/BlogController.cs
using Microsoft.AspNetCore.Mvc;
using MyAspNetCoreApp.Web.Filters;

namespace MyAspNetCoreApp.Web.Controllers;

[Route("[controller]/[action]")]
public class BlogController : Controller
{
    [CustomResultFilter("x-version", "1.0")]
    [HttpGet("{name}/{id}")]
    public IActionResult Article(string name, int id)
    {
        var routes = Request.RouteValues["article"];
        return View();
    }
    
}

AspNetCore.MVC/TurkcellBootcamp/Camp_301/MyAspNetCoreApp/MyAspNetCoreApp.Web/Controllers/ProductsController.cs
using AutoMapper;
using AutoMapper.QueryableExtensions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.FileProviders;
using MyAspNetCoreApp.Web.Filters;
using MyAspNetCoreApp.Web.Models;
using MyAspNetCoreApp.Web.ViewModels;

namespace MyAspNetCoreApp.Web.Controllers;

[Route("[controller]/[action]")]
public class ProductsController : Controller
{
    private readonly IMapper _mapper;
    private readonly AppDbContext _context;
    private readonly IFileProvider _fileProvider;
    
    public ProductsController(AppDbContext context, IMapper mapper, IFileProvider fileProvider)
    {
        _context = context;
        _mapper = mapper;
        _fileProvider = fileProvider;

        _context.SaveChanges();
    }
    // [CacheResourceFilter]
    public IActionResult Index()
    {
        List<ProductViewModel> products = _context.Products.Include(x => x.Category).Select(x => new ProductViewModel()
        {
            Id = x.Id,
            Name = x.Name,
            Price = x.Price,
            Stock = x.Stock,
            CategoryName = x.Category.Name,
            Color = x.Color,
            Description = x.Description,
            Expire = x.Expire,
            ImagePath = x.ImagePath,
            IsPublish = x.IsPublish,
            PublishDate = x.PublishDate

        }).ToList();
        
        return View(products);
    }
    [Route("[controller]/[action]/{productId}", Name = "product")]
    [ServiceFilter(typeof(NotFoundFilter))]
    public IActionResult GetById(int productId)
    {
        var product = _context.Products.Find(productId);

        return View(_mapper.Map<ProductViewModel>(product));
    }
    [Route("[controller]/[action]/{page}/{pageSize}",Name = "productPage")]
    public IActionResult Pages(int page, int pageSize)
    {
        var products = _context.Products.Skip((page - 1) * pageSize).Take(pageSize).ToList();
        
        ViewBag.page = page;
        ViewBag.pageSize = pageSize;
        
        return View(_mapper.Map<List<ProductViewModel>>(products));
    }
    [ServiceFilter(typeof(NotFoundFilter))]
    public IActionResult Remove(int id)
    {
        var product = _context.Products.Find(id);
        _context.Products.Remove(product);
        _context.SaveChanges();
        return RedirectToAction("Index");
    }
    public IActionResult Add()
    {
        ViewBag.Expire = new Dictionary<string, int>()
        {
            { "1 Month", 1},
            { "3 Month", 3},
            { "6 Month", 6},
            { "12 Month", 12}
        };

        ViewBag.Color = new SelectList(new List<ColorSelectList>
        {
          new() {Data = "Black", Value = "Black"},  
          new() {Data = "Gray", Value = "Gray"}, 
          new() {Data = "White", Value = "White"}  
        },"Value", "Data");

        var categories = _context.Category.ToList();

        ViewBag.categorySelect = new SelectList(categories, "Id", "Name");

        return View();
    }
    [HttpPost]
    public IActionResult Add(ProductViewModel newProduct)
    {
        IActionResult result = null;
        
        if (ModelState.IsValid)
        {
            try
            {
                var product = _mapper.Map<Product>(newProduct);

                if (newProduct.Image is { Length: > 0 })
                {
                    var root = _fileProvider.GetDirectoryContents("wwwroot");
                    var images = root.First(x => x.Name == "images");
                    var randomImageName = Guid.NewGuid() + Path.GetExtension(newProduct.Image.FileName);
                    var path = Path.Combine(images.PhysicalPath, randomImageName);
                    using var stream = new FileStream(path, FileMode.Create);
                    newProduct.Image.CopyTo(stream);
                
                    product.ImagePath = randomImageName;
                }
                
                _context.Products.Add(product);
                _context.SaveChanges();
                TempData["status"] = "Product has been successfully added";
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                // ModelState.AddModelError("error", new ErrorViewModel()
                // {
                //     Errors = new List<string>(){"Problem occurred when saving data, please try again"}
                // }.ToString());
                result = View();
            }
        }
        else
        {
            result = View();
        }

        var categories = _context.Category.ToList();
        ViewBag.categorySelect = new SelectList(categories,"Id", "Name");

        ViewBag.Expire = new Dictionary<string, int>()
        {
            { "1 Month", 1},
            { "3 Month", 3},
            { "6 Month", 6},
            { "12 Month", 12}
        };

        ViewBag.Color = new SelectList(new List<ColorSelectList>
        {
            new() {Data = "Black", Value = "Black"},  
            new() {Data = "Gray", Value = "Gray"}, 
            new() {Data = "White", Value = "White"}  
        },"Value", "Data");

        return result;
    }
    [ServiceFilter(typeof(NotFoundFilter))]
    public IActionResult Update(int id)
    {
        var product = _context.Products.Find(id);
        var categories = _context.Category.ToList();
        
        ViewBag.categorySelect = new SelectList(categories,"Id", "Name",product.CategoryId);


        ViewBag.ExpireValue = product.Expire;
        
        ViewBag.Expire = new Dictionary<string, int>()
        {
            { "1 Month", 1},
            { "3 Month", 3},
            { "6 Month", 6},
            { "12 Month", 12}
        };

        ViewBag.Color = new SelectList(new List<ColorSelectList>
        {
            new() {Data = "Black", Value = "Black"},  
            new() {Data = "Gray", Value = "Gray"}, 
            new() {Data = "White", Value = "White"}  
        },"Value", "Data", product.Color);
        
        return View(_mapper.Map<ProductUpdateViewModel>(product));
    }
    [HttpPost]
    public IActionResult Update(ProductUpdateViewModel updatedProduct)
    {
        if (!ModelState.IsValid)
        {
            ViewBag.ExpireValue = updatedProduct.Expire;
        
            ViewBag.Expire = new Dictionary<string, int>()
            {
                { "1 Month", 1},
                { "3 Month", 3},
                { "6 Month", 6},
                { "12 Month", 12}
            };

            ViewBag.Color = new SelectList(new List<ColorSelectList>
            {
                new() {Data = "Black", Value = "Black"},  
                new() {Data = "Gray", Value = "Gray"}, 
                new() {Data = "White", Value = "White"}  
            },"Value", "Data", updatedProduct.Color);
            
            var categories = _context.Category.ToList();
            
            ViewBag.categorySelect = new SelectList(categories,"Id", "Name",updatedProduct.CategoryId);

            return View();
        }
        if (updatedProduct.Image is { Length: > 0 })
        {
            var root = _fileProvider.GetDirectoryContents("wwwroot");
            var images = root.First(x => x.Name == "images");
            var randomImageName = Guid.NewGuid() + Path.GetExtension(updatedProduct.Image.FileName);
            var path = Path.Combine(images.PhysicalPath, randomImageName);
            using var stream = new FileStream(path, FileMode.Create);
            updatedProduct.Image.CopyTo(stream);
                
            updatedProduct.ImagePath = randomImageName;
        }
        _context.Products.Update(_mapper.Map<Product>(updatedProduct));
        _context.SaveChanges();
        TempData["status"] = "Product has been successfully updated";
        return RedirectToAction("Index");
    }
    [AcceptVerbs("GET", "POST")]
    public IActionResult HasProductName(string name)
    {
        var isProductNameExists = _context.Products.Any(x => x.Name.ToLower() == name.ToLower());

        if (isProductNameExists)
        {
            return Json($"The product with the name {name} has exists. Please try different name for the product.");
        }

        return Json(true);
    }
}

AspNetCore.MVC/TurkcellBootcamp/Camp_301/MyAspNetCoreApp/MyAspNetCoreApp.Web/Views/Products/Add.cshtml
@{
    ViewBag.Title = "Add Product";
    Layout = "_Layout";
}
@model ProductViewModel

<h2>Add Product</h2>
<div asp-validation-summary="ModelOnly"></div>

<form asp-controller="Products" asp-action="Add" method="post" enctype="multipart/form-data">
    
  <div class="mb-3">
    <label asp-for="Name" class="form-label">Name</label>
    <input class="form-control" asp-for="Name">
    <span class="text-danger" asp-validation-for="Name"></span>
  </div>
  
  <div class="mb-3">
    <label asp-for="Price" class="form-label">Price</label>
    <input class="form-control" asp-for="Price">
    <span class="text-danger" asp-validation-for="Price"></span>
  </div>
  
  <div class="mb-3">
    <label asp-for="Stock" class="form-label">Stock</label>
    <input type="number" class="form-control" asp-for="Stock">
    <span class="text-danger" asp-validation-for="Stock"></span>
  </div>
  
  <div class="mb-3">
    <label asp-for="Color" class="form-label">Color</label>
    <select class="form-select" asp-for="Color" asp-items="@ViewBag.Color">
      <option value="">Please select the color of your product</option>
    </select>
    <span class="text-danger" asp-validation-for="Color"></span>
  </div>
  
  <div class="form-check">
    <input class="form-check-input" asp-for="IsPublish">
    <label asp-for="IsPublish" for="flexCheckDefault">
      Publish Product
    </label>
  </div>
  
  <div class="mb-3 mt-3">
    <span>How long should this product be published on our website?</span>
    @foreach (var item in ViewBag.Expire as Dictionary<string, int>)
    {
      <div class="form-check m-1">
        <input class="form-check-input" type="radio" asp-for="Expire" id="@(item.Value)Expire" value="@item.Value">
        <label class="form-check-label" asp-for="Expire" for="@(item.Value)Expire">
          @item.Key
        </label>
      </div>
    }
    <span class="text-danger" asp-validation-for="Expire"></span>
  </div>
  
  <div class="mb-3">
    <label asp-for="PublishDate" class="form-label">Publish Date</label>
    <input class="form-control" asp-for="PublishDate">
    <span class="text-danger" asp-validation-for="PublishDate"></span>
  </div>
  
  <div class="form-floating mb-3">
    <textarea asp-for="Description" class="form-control" placeholder="Please enter the description of your product here" style="height: 100px"></textarea>
    <label asp-for="Description">Description</label>
    <span class="text-danger" asp-validation-for="Description"></span>
  </div>
  
  <div class="mb-3">
    <label asp-for="Email" class="form-label">Email Address</label>
    <input type="text" class="form-control" asp-for="Email">
    <span class="text-danger" asp-validation-for="Email"></span>
  </div>
  
  <div class="mb-3">

    <select class="form-select" asp-for="CategoryId" asp-items="@ViewBag.categorySelect">
      <option value="">Please select a category</option>
    </select>
    <span class="text-danger" asp-validation-for="CategoryId"></span>

  </div>

  <div>
    <label for="formFileLg" class="form-label">Product Image</label>
    <input class="form-control form-control-lg mb-3" asp-for="Image" type="file">
  </div>

  <button class="btn btn-dark" type="submit">Save Product</button>
</form>

AspNetCore.MVC/TurkcellBootcamp/Camp_301/MyAspNetCoreApp/MyAspNetCoreApp.Web/Views/Products/GetById.cshtml
@model ProductViewModel

@{
    ViewBag.Title = "Product";
    Layout = "_Layout";
}

<a class="btn btn-primary mb-3" asp-controller="Products" asp-action="Index">Go to the products</a>

<h2>Product @Model.Name</h2>

<div>
    <ul>
        <li>
            Id: @Model.Id
        </li>
        <li>
            Name: @Model.Name
        </li>
        <li>
            Price: @Model.Price
        </li>
        <li>
            Stock: @Model.Stock
        </li>
        <li>
            Color: @Model.Color
        </li>
        <li>
            Publish Time: @Model.Expire
        </li>
        <li>
            Publish Status: @Model.IsPublish
        </li>
        <li>
            Publish Date: @Model.PublishDate
        </li>
        <li>
            Description: @Model.Description
        </li>
    </ul>
</div>

AspNetCore.MVC/TurkcellBootcamp/Camp_301/MyAspNetCoreApp/MyAspNetCoreApp.Web/Views/Products/Index.cshtml
@{
    ViewBag.Title = "Products";
    Layout = "_Layout";
}


<h2>Products</h2>
@if(TempData["status"] != null)
    {
        <div class="alert alert-dark" role="alert">
            @TempData["status"]
        </div>
    }
@model List<ProductViewModel>
<a asp-controller="Products" asp-action="Add">Add Product</a>
<table class="table">
    <thead>
    <tr>
        <th>Id</th>
        <th>Image</th>
        <th>Category</th>
        <th>Name</th>
        <th>Price</th>
        <th>Stock</th>
        <th>Color</th>
        <th>Publish Status</th>
        <th>Publish Time</th>
        <th>Description</th>
        <th>Operation</th>
    </tr>
    </thead>
    <tbody>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.Id</td>
            <td>
                @if (!string.IsNullOrEmpty(item.ImagePath))
                {
                    <img style="width: 100px; height: 100px;" src="/images/@(item.ImagePath)"/>
                }
                else
                {
                    <img style="width: 100px; height: 100px;" src="/images/No-Image-Placeholder.svg.png"/>

                }
            </td>
            <td>@item.CategoryName</td>
            <td>@item.Name</td>
            <td>@item.Price</td>
            <td>@item.Stock</td>
            <td>@item.Color</td>
            <td>@(item.IsPublish ? "Active" : "Passive")</td>
            <td>@item.Expire</td>
            <td>
                @if (item.Description.Length > 20)
                {
                    @item.Description[..20]<text>...</text>
                }
                else
                {
                    @item.Description
                }
            </td>
            <td>
                <a asp-controller="Products" asp-action="Remove" asp-route-id="@item.Id">Delete</a>
                <a asp-controller="Products" asp-action="Update" asp-route-id="@item.Id">Update</a>
                <a asp-route="product" asp-route-productId="@item.Id">Show</a>
            </td>
        </tr>    
    }
    </tbody>
</table>
<div>
    <a asp-route="productPage" asp-route-page="1" asp-route-pageSize="3">First page with 3 items</a>
    <a asp-route="productPage" asp-route-page="2" asp-route-pageSize="3">Second page with 3 items</a>
</div>

<div>
    <a asp-controller="Blog" asp-action="Article" asp-route-name="article-name" asp-route-id="1">First article</a>
</div>

AspNetCore.MVC/TurkcellBootcamp/Camp_301/MyAspNetCoreApp/MyAspNetCoreApp.Web/Views/Products/Pages.cshtml
@model List<ProductViewModel>

@{
    ViewBag.Title = "Pages";
    Layout = "_Layout";
}

<h2>Page: @ViewBag.page</h2>
<h2>Page Size: @ViewBag.pageSize</h2>

<table class="table">
    <thead>
    <tr>
        <th>Id</th>
        <th>Name</th>
        <th>Price</th>
        <th>Stock</th>
        <th>Color</th>
        <th>Publish Status</th>
        <th>Publish Time</th>
        <th>Description</th>
        <th>Operation</th>
    </tr>
    </thead>
    <tbody>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.Id</td>
            <td>@item.Name</td>
            <td>@item.Price</td>
            <td>@item.Stock</td>
            <td>@item.Color</td>
            <td>@(item.IsPublish ? "Active" : "Passive")</td>
            <td>@item.Expire</td>
            <td>
                @if (item.Description.Length > 20)
                {
                    @item.Description[..20]<text>...</text>
                }
                else
                {
                    @item.Description
                }
            </td>
            <td>
                <a asp-controller="Products" asp-action="Remove" asp-route-id="@item.Id">Delete</a>
                <a asp-controller="Products" asp-action="Update" asp-route-id="@item.Id">Update</a>
                <a asp-controller="Products" asp-action="GetById" asp-route-id="@item.Id">Show</a>
            </td>
        </tr>    
    }
    </tbody>
</table>

AspNetCore.MVC/TurkcellBootcamp/Camp_301/MyAspNetCoreApp/MyAspNetCoreApp.Web/Views/Products/Update.cshtml
@{
    ViewBag.Title = "Update Product";
    Layout = "_Layout";
}

<h2>Update Product</h2>

@model ProductUpdateViewModel

<form asp-controller="Products" asp-action="Update" method="post" enctype="multipart/form-data">
  <input type="hidden" asp-for="Id"/>
  <input type="hidden" asp-for="ImagePath"/>
  <div>
    <img style="width: 100px; height: 100px;" src="@(string.IsNullOrEmpty(Model.ImagePath) ? "/images/No-Image-Placeholder.svg.png":"/images/"+Model.ImagePath)" />
  </div>
  <div class="mb-3">
    <label asp-for="Name" class="form-label">Name</label>
    <input class="form-control" asp-for="Name">
    <span class="text-danger" asp-validation-for="Name"></span>
  </div>
  
  <div class="mb-3">
    <label asp-for="Price" class="form-label">Price</label>
    <input class="form-control" asp-for="Price">
    <span class="text-danger" asp-validation-for="Price"></span>
  </div>
  
  <div class="mb-3">
    <label asp-for="Stock" class="form-label">Stock</label>
    <input class="form-control" asp-for="Stock">
    <span class="text-danger" asp-validation-for="Stock"></span>
  </div>
  
  <div class="mb-3">
    <label asp-for="Color" class="form-label">Color</label>
    <select class="form-select" asp-for="Color" asp-items="@ViewBag.Color">
      <option value="">Please select the color of your product</option>
    </select>
    <span class="text-danger" asp-validation-for="Color"></span>
  </div>
  
  <div class="form-check">
    <input class="form-check-input" asp-for="IsPublish">
    <label asp-for="IsPublish" for="flexCheckDefault">
      Publish Product
    </label>
  </div>
  
  <div class="mb-3 mt-3">
  <span>How long should this product be published on our website?</span>
  @foreach (var item in ViewBag.Expire as Dictionary<string, int>)
  {
    <div class="form-check m-1">

      <input checked=@(item.Value == ViewBag.ExpireValue) class="form-check-input" type="radio" asp-for="Expire" id="@(item.Value)Expire" value="@item.Value">

      <label class="form-check-label" asp-for="Expire" for="@(item.Value)Expire">
        @item.Key
      </label>
    </div>
  }
  <span class="text-danger" asp-validation-for="Expire"></span>
  
  
  <div class="mb-3">
    <label asp-for="PublishDate" class="form-label">Publish Date</label>
    <input class="form-control" asp-for="PublishDate">
    <span class="text-danger" asp-validation-for="PublishDate"></span>
  </div>
  
  <div class="form-floating mb-3">
    <textarea asp-for="Description" class="form-control" placeholder="Please enter the description of your product here" style="height: 100px"></textarea>
    <label asp-for="Description">Description</label>
    <span class="text-danger" asp-validation-for="Description"></span>
  </div>
  
  <div class="mb-3">
    <label asp-for="CategoryId" class="form-label">Category</label>
    <select class="form-select" asp-for="CategoryId" asp-items="@ViewBag.categorySelect">
      <option value="">Please select the category of your product</option>
    </select>
    <span class="text-danger" asp-validation-for="CategoryId"></span>
  </div>
  
  <div>
    <label for="formFileLg" class="form-label">Product Image</label>
    <input class="form-control form-control-lg mb-3" asp-for="Image" type="file">
  </div>
  <button class="btn btn-dark" type="submit">Update Product</button>
  </div>
</form>